### ISSUE TITLE
Automate release

### ISSUE THREAD

**Issue by tuhinmallick** [CorrelAid/DataToMetabase#24]
This helped me pretty much.
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

**Comment by KonradUdoHannes** [comment]
I think without an active userbase package releases and their automation are not well spend effort. At the same time I think CI functionality really helps to make the project maintainable and that was implemented in #43. Consequently I'll close this issue.
