### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by tuhinmallick** [CorrelAid/DataToMetabase#25]
Create database

request_data = {
            "name": name,
            "engine": engine,
            "details": {
                "host": host,
                "port": port,
                "dbname": dbname,
                "user": user,
                "password": password,
                "ssl": ssl,
                "tunnel_port": tunnel_port
            }
        }

Where ssl = False and tunnel port is 22

**Comment by KonradUdoHannes** [comment]
Following up on the previous comment I'll close this issue (and #26) for now.
