### ISSUE TITLE
devtools is required but not in renv

### ISSUE THREAD

**Issue by philippolis** [CorrelAid/DataToMetabase#34]
To load the project `devtools::load_all()` must be run, should `devtools` be part of renv then?

**Comment by KonradUdoHannes** [comment]
Should be fixed with #38

**Comment by KonradUdoHannes** [comment]
@philippolis As I understood, you tested that this, and it is indeed fixed. If so please close this issue.

**Comment by philippolis** [comment]
@KonradUdoHannes thanks for adding `devtools` to renv
