### ISSUE TITLE
package "vcr" is required but not part of renv

### ISSUE THREAD

**Issue by philippolis** [CorrelAid/DataToMetabase#35]
Running `devtools::load_all()` yielded the following error

`Error in library("vcr") : there is no package called ‘vcr’`

Consequently,
```
install.packages(”vcr”)
devtool::load_all()
```
succeeded

**Comment by KonradUdoHannes** [comment]
Should be fixed now with #38

**Comment by KonradUdoHannes** [comment]
@philippolis As I understood, you tested that this, and it is indeed fixed. If so please close this issue.

**Comment by philippolis** [comment]
@KonradUdoHannes Thanks for adding `vcr` to the renv :)
